#!/usr/bin/env python3
"""
Sync the WORKFLOWS array in artifact/command.html from docs/port-manifest.md.

v3 architecture: 15 Library entry cards (Jobs-To-Be-Done), each binding 1+ spoke skills.
Spokes are hidden from the Library; reachable only via orchestrator or named chains.

Reads:
    docs/port-manifest.md · canonical source of truth for skill inventory
        Specifically the "The 15 entry cards" table

Writes:
    artifact/command.html · regenerates the WORKFLOWS JS array

Run from plugin root:
    python3 scripts/sync-workflows.py
"""

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MANIFEST = ROOT / "docs" / "port-manifest.md"
DASHBOARD = ROOT / "artifact" / "command.html"

# Visual taglines for each entry card · keep these brand-voiced + short
CARD_TAGLINES = {
    "Launch something new": "product, bundle, sale, subscription",
    "Fix something broken": "flow, funnel, page, copy",
    "Why did X drop?": "diagnose the leak",
    "Where to focus this month?": "priority + leverage",
    "Make this week's creative": "ads + concepts",
    "Make this week's content": "TikTok, Reddit, IG organic",
    "Run the email machine": "build, send, audit, copy",
    "Handle this customer": "reply or review response",
    "Check the competition": "scan, deep dive, ad library",
    "Prep a paid campaign": "Meta, Google, Bing, Reddit ads",
    "Amazon ops": "listing, restock, S&S",
    "Weekly review": "what shipped, what won, next week",
    "Listen to customers": "reviews + surveys",
    "CRO deep dive": "heatmap, session, GA4, polls",
    "SEO + content": "audit, keywords, briefs, writing",
}


def parse_entry_cards(manifest_text):
    """Extract the 15 entry cards table from port-manifest.md."""
    # Find "## The 15 entry cards" section
    m = re.search(r"^## The 15 entry cards.*?\n\n(.+?)(?=\n##|\Z)", manifest_text, re.DOTALL | re.MULTILINE)
    if not m:
        sys.exit("ERROR: Could not find '## The 15 entry cards' section in port-manifest.md")
    
    section = m.group(1)
    cards = []
    # Match table rows like: | 1 | Card title | spoke1 · spoke2 · spoke3 |
    for row_match in re.finditer(r"^\|\s*(\d+)\s*\|\s*([^|]+?)\s*\|\s*([^|]+?)\s*\|", section, re.MULTILINE):
        num = int(row_match.group(1))
        title = row_match.group(2).strip()
        spokes_raw = row_match.group(3).strip()
        # Split spokes by ' · '
        spokes = [s.strip() for s in spokes_raw.split('·') if s.strip()]
        cards.append({
            "num": num,
            "title": title,
            "tagline": CARD_TAGLINES.get(title, ""),
            "spokes": spokes,
        })
    
    if not cards:
        sys.exit("ERROR: No card rows parsed")
    print(f"Parsed {len(cards)} entry cards from manifest")
    return cards


def build_workflows_js(cards):
    """Build the JS WORKFLOWS array · one entry per card."""
    items = []
    for card in cards:
        title_escaped = card["title"].replace("'", "\\'")
        tagline_escaped = card["tagline"].replace("'", "\\'")
        spokes_str = ', '.join(f"'{s}'" for s in card["spokes"])
        items.append(
            f"  {{ num: {card['num']}, title: '{title_escaped}', tagline: '{tagline_escaped}', spokes: [{spokes_str}] }}"
        )
    return "const WORKFLOWS = [\n" + ",\n".join(items) + "\n];"


def main():
    if not MANIFEST.exists():
        sys.exit(f"port-manifest.md not found at {MANIFEST}")
    if not DASHBOARD.exists():
        sys.exit(f"artifact/command.html not found at {DASHBOARD}")
    
    manifest_text = MANIFEST.read_text()
    cards = parse_entry_cards(manifest_text)
    workflows_js = build_workflows_js(cards)
    
    html = DASHBOARD.read_text()
    pattern = re.compile(r"// Workflow catalog.*?\nconst WORKFLOWS = \[.*?\n\];", re.DOTALL)
    if not pattern.search(html):
        pattern = re.compile(r"const WORKFLOWS = \[.*?\n\];", re.DOTALL)
        if not pattern.search(html):
            sys.exit("ERROR: Could not find WORKFLOWS array in dashboard HTML")
    
    new_block = "// Workflow catalog · 15 entry cards · generated by scripts/sync-workflows.py from docs/port-manifest.md · do not hand-edit\n" + workflows_js
    new_html = pattern.sub(new_block, html, count=1)
    DASHBOARD.write_text(new_html)
    
    total_spokes = sum(len(c["spokes"]) for c in cards)
    print(f"OK Dashboard WORKFLOWS array regenerated · {len(cards)} entry cards · {total_spokes} spoke bindings")


if __name__ == "__main__":
    main()
